<a href="https://colab.research.google.com/github/Agam8118/Python_basics/blob/main/Worksheet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#1
import numpy as np
from scipy import stats

arr = np.random.randint(10,40,(1,10))
print(arr)
print(stats.tmean(arr))

[[13 35 32 16 18 24 21 31 34 14]]
23.8


In [11]:
#2
from scipy.fftpack import fft2
A = np.random.randint(10,31,(3,3))
print(A)
print(fft2(A))

[[24 29 11]
 [23 11 11]
 [22 13 25]]
[[169.  -0.j          19.  -5.19615242j  19.  +5.19615242j]
 [ 11.5+12.99038106j -12.5-28.57883832j   5.5+12.99038106j]
 [ 11.5-12.99038106j   5.5-12.99038106j -12.5+28.57883832j]]
