<a href="https://colab.research.google.com/github/Agam8118/Python_basics/blob/main/Worksheet4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.1
import numpy as np

arr = np.random.randint(5,26,(1,10))
print(arr)

[[16 21 21  8  7 21 18 19 20 15]]


In [ ]:
#1.2
arr1 = np.random.randint(10,51,size=(3,4))
print(arr1)

[[21 31 28 28]
 [12 23 22 38]
 [18 44 20 49]]


In [ ]:
#2.1
print(arr.shape)
print(arr.size)
print(arr.dtype)

(1, 10)
10
int64


In [ ]:
#2.2
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

(3, 4)
12
int64


In [ ]:
#3.1
array1 = np.array([2,4,6,8,10])
array2 = np.array([1,3,5,7,9])
print(array1)
print(array2)

[ 2  4  6  8 10]
[1 3 5 7 9]


In [ ]:
#3.2
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)

[ 3  7 11 15 19]
[1 1 1 1 1]
[ 2 12 30 56 90]
[2.         1.33333333 1.2        1.14285714 1.11111111]


In [ ]:
#4.1
Arrar = np.arange(1,10).reshape(3,3)
print(Arrar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#4.2
result = Arrar*5
print(result)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
#5.1
a = np.random.randint(10,26,size=(4,4))
print(a)

[[13 19 19 24]
 [15 14 15 22]
 [25 14 16 18]
 [24 25 24 19]]


In [ ]:
#5.2
print(a[1,0:4])

[15 14 15 22]


In [ ]:
#5.3
print(a[0:4,3])

[24 22 18 19]


In [ ]:
#6.1
ar = np.random.randint(20,40,10)
print(ar)

[29 36 39 26 34 27 28 23 20 36]


In [ ]:
boo = ar>30
print(boo)

[False  True  True False  True False False False False  True]


In [ ]:
#7.1
a = np.random.randint(11,size=(12,))
print(a)

[ 4  3  2  3 10  5  1  6  1  9  7  7]


In [ ]:
#7.2
a = np.reshape(a,(3,4))
print(a)

[[ 4  3  2  3]
 [10  5  1  6]
 [ 1  9  7  7]]


In [ ]:
#8.1
matA = np.array([[1,2],[3,4]])
matB = np.array([[5,6],[7,8]])
print(matA)
print(matB)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
#8.2
print(matA*matB)
print(matA.dot(matB))
print(np.transpose(matA))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
#9.1
a = np.random.randint(10,61,(1,15))
print(a)

[[31 28 57 24 32 22 48 45 51 34 31 22 20 11 17]]


In [ ]:
#9.2
print(np.mean(a))
print(np.median(a))
print(np.std(a))

31.533333333333335
31.0
12.919580316541076


In [ ]:
#10.1
A = np.array([[2,1,3],[0,5,6],[7,8,9]])
print(A)

[[2 1 3]
 [0 5 6]
 [7 8 9]]


In [ ]:
#10.2
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(np.linalg.eig(A))

-68.99999999999996
[[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]
EigResult(eigenvalues=array([15.45215427,  2.40475147, -1.85690573]), eigenvectors=array([[-0.22453607, -0.55941438, -0.38300969],
       [-0.48513596,  0.7607706 , -0.60830181],
       [-0.84511931, -0.3290648 ,  0.69517803]]))
